# Permalinks
permalink:           pretty

# Setup
title:               From A to Z,
tagline:             Stuck in the middle with you
url:                 https://azni615.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              A. Z. Ni
  url:               https://twitter.com/zaglamir
  email:             azni615@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/azni615/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
